Feature/encryption with context
temporalio/samples-go pull request #87
Opened 2021-03-28 22:51 UTC by robholland

## What was changed:

## Why?

## Closes issue: 

## How has this been tested?

## Any docs updates needed?

2021-04-02 16:51 UTC, Sushisource commented on cryptconverter/plugin/main.go
> +	MagicCookieValue: "cookie",
I think it's probably best practice to make this a little more application-specific, even though this is a sample people are probably going to copy-paste things like this wholesale

2021-04-02 16:52 UTC, Sushisource commented on cryptconverter/data-converter.go
> +	// Key can be fetched from KMS or other secure storage.
nit: I'd probably make this wording stronger. Maybe even "*must* be fetched ... in a production setting"

2021-04-02 16:53 UTC, Sushisource approved these changes
Looks great, thanks Rob! Just a few minor wording changes

2021-04-10 01:45 UTC, mfateev commented on cryptconverter/cryptconverter.go
> +	// once the activity completes.
You can test this differently. Let activity timeout and the result of the last heartbeat will be included in the timeout error.

2021-04-26 18:09 UTC, feedmeapples requested changes

2021-04-26 18:09 UTC, feedmeapples commented on go.mod
> +replace go.temporal.io/sdk => /Users/rob/Code/github.com/robholland/sdk-go
leftover

2021-04-26 18:09 UTC, feedmeapples commented on go.mod
> +replace go.temporal.io/sdk => /Users/rob/Code/github.com/robholland/sdk-go
```suggestion
```

2021-04-26 18:10 UTC, feedmeapples commented on go.mod
> +replace go.temporal.io/server => /Users/rob/Code/github.com/robholland/temporal
```suggestion
```

2021-04-26 18:10 UTC, feedmeapples commented on go.mod
> +
```suggestion
```

2021-04-26 18:11 UTC, feedmeapples commented on go.mod
> +
```suggestion
```

2021-04-28 19:31 UTC, feedmeapples commented on go.mod
> +replace go.temporal.io/server => github.com/robholland/temporal v1.1.1-0.20210427090742-bc9685c643ea
this needs to be cleaned before merging ^

2021-04-28 19:32 UTC, feedmeapples requested changes

2021-04-28 19:32 UTC, feedmeapples commented on go.mod
> +	go.temporal.io/server v0.0.0-00010101000000-000000000000
and this ^

2021-05-13 17:23 UTC, feedmeapples commented on cryptconverter/README.md
> +go build -o ./cryptconverter-plugin plugin/main.go
let's add the resulting binary to gitignore as the built artifact

2021-05-13 17:28 UTC, feedmeapples approved these changes

2021-05-14 16:23 UTC, merged